version: 0.17-0

mqtt:
  enabled: true
  host: mqtt
  port: 1883

detectors:
  apple_silicon:
    type: zmq
    endpoint: tcp://host.docker.internal:5555

model:
  path: /config/model_cache/yolo.onnx
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float

objects:
  track:
    - person
    - car
    - dog

record:
  enabled: true

go2rtc:
  streams:
    cam1_main:
      - "ffmpeg:http://192.168.1.234/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}#video=copy#audio=copy"
    cam1_sub:
      - "ffmpeg:http://192.168.1.234/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}"

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
