services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable-standard-arm64
    shm_size: "256mb"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
    extra_hosts:
      - "host.docker.internal:host-gateway"
